Create args-print
jaceklaskowski/scala-academy-sandbox pull request #3
Opened 2022-05-05 12:14 UTC by MateuszSab

Mateusz project

2022-05-05 12:22 UTC, jaceklaskowski requested changes
1. Use `src/main/scala` for the app
2. Where are the other files (e.g. `build.sbt`, `project.properties`)?

2022-05-05 12:25 UTC, MateuszSab commented
fixed, I hope

2022-05-05 12:28 UTC, jaceklaskowski requested changes
1. `project/target` to be deleted
2. `project/project/target/` to be deleted too
3. `README.md` missing?

2022-05-05 12:39 UTC, MateuszSab commented
what is wrong this time?

2022-05-05 18:55 UTC, MateuszSab commented
Czy teraz jest w porządku?

2022-05-06 07:14 UTC, jaceklaskowski requested changes
1. All the files should go under `docker-scopt`

2022-05-06 07:14 UTC, jaceklaskowski commented on mateusz/README.md
> +My scopt project
1. No title?!
2. How to build and run?

2022-05-06 07:29 UTC, MateuszSab commented
files refactored, readme updated

2022-05-06 09:38 UTC, merged